// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1buEa6psFC7VuhRYRnZd6I7F29aaZqn0',
    appId: '1:537450866347:web:7ad1e3bf12ac3c15e6b9ee',
    messagingSenderId: '537450866347',
    projectId: 'ia-outreach-app',
    authDomain: 'ia-outreach-app.firebaseapp.com',
    storageBucket: 'ia-outreach-app.appspot.com',
    measurementId: 'G-SWYCL9LV0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi-ITW_4sDM3AidleU4hLWhVUYqenQWtc',
    appId: '1:537450866347:android:18daba6e0c3c5df2e6b9ee',
    messagingSenderId: '537450866347',
    projectId: 'ia-outreach-app',
    storageBucket: 'ia-outreach-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUsOZEkNhwnymOhb31W-vUSaxCfWijbeE',
    appId: '1:537450866347:ios:ac8b8192b3c80b68e6b9ee',
    messagingSenderId: '537450866347',
    projectId: 'ia-outreach-app',
    storageBucket: 'ia-outreach-app.appspot.com',
    iosBundleId: 'com.example.outreachapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUsOZEkNhwnymOhb31W-vUSaxCfWijbeE',
    appId: '1:537450866347:ios:ac8b8192b3c80b68e6b9ee',
    messagingSenderId: '537450866347',
    projectId: 'ia-outreach-app',
    storageBucket: 'ia-outreach-app.appspot.com',
    iosBundleId: 'com.example.outreachapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1buEa6psFC7VuhRYRnZd6I7F29aaZqn0',
    appId: '1:537450866347:web:823cfc206d08fc52e6b9ee',
    messagingSenderId: '537450866347',
    projectId: 'ia-outreach-app',
    authDomain: 'ia-outreach-app.firebaseapp.com',
    storageBucket: 'ia-outreach-app.appspot.com',
    measurementId: 'G-GF8HWRE08W',
  );
}